quarkus.default-locale=pt-BR

quarkus.http.host=0.0.0.0
quarkus.http.port=3000

%dev,prod.quarkus.datasource.jdbc.url=jdbc:mysql://db:3306/${DB_DATABASE}?allowMultiQueries=true
%dev,prod.quarkus.datasource.username=${DB_USER}
%dev,prod.quarkus.datasource.password=${DB_PASSWORD}

quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.validate-in-dev-mode=false

quarkus.flyway.migrate-at-start=true
quarkus.flyway.out-of-order=true
%test.quarkus.datasource.jdbc.additional-jdbc-properties.allowMultiQueries=true
%test.quarkus.datasource.devservices.image-name=mysql:8.4.0
%test.quarkus.jacoco.excludes=org/example/jooq/**
%prod.quarkus.flyway.out-of-order=false
